# Generated by Django 4.0 on 2021-12-30 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicClassInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_code",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "class_section",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("year", models.IntegerField()),
                (
                    "semester",
                    models.IntegerField(
                        choices=[(1, "Spring"), (2, "Summer"), (3, "Fall")]
                    ),
                ),
                (
                    "min_units",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "max_units",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
