# Generated by Django 4.0 on 2022-02-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_basicclassinfo_max_units_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="basicclassinfo",
            name="class_section",
        ),
        migrations.AddField(
            model_name="basicclassinfo",
            name="class_number",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="BasicClassSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=50)),
                ("session", models.CharField(max_length=3)),
                (
                    "section_type",
                    models.IntegerField(
                        choices=[
                            (1, "Lecture"),
                            (2, "Discussion"),
                            (3, "Lab"),
                            (4, "Quiz"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("days", models.CharField(default="0000000", max_length=7)),
                ("location_building", models.CharField(max_length=50)),
                (
                    "location_room",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "class_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_section",
                        to="classes.basicclassinfo",
                    ),
                ),
                (
                    "instructor",
                    models.ManyToManyField(
                        related_name="classes", to="classes.Instructor"
                    ),
                ),
            ],
        ),
    ]
